name: Build Patched APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 步骤 1: 直接检出您已经修改过的仓库
    - name: Checkout your repository
      uses: actions/checkout@v4

    # 步骤 2: 设置环境并构建
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    # 步骤 3: 上传构建产物
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MixFile-patched-apk
        path: app/build/outputs/apk/release/app-release.apk