name: Build on Upstream Release

on:
  schedule:
    # 每天执行一次，检查上游是否有新版本
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your fork
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Get the latest tag from upstream
      id: get_tag
      run: |
        LATEST_TAG=$(git ls-remote --tags --sort="v:refname" https://github.com/InvertGeek/mixfile.git | tail -n1 | sed 's/.*\///')
        echo "Latest tag is $LATEST_TAG"
        echo "::set-output name=tag::$LATEST_TAG"

    - name: Checkout the latest tag
      run: git checkout ${{ steps.get_tag.outputs.tag }}

    - name: Apply patch
      run: git apply --ignore-whitespace webdav-downloader.patch

    - name: Build with Gradle
      run: ./gradlew :app:assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: patched-mixfile-apk-${{ steps.get_tag.outputs.tag }}
        path: app/build/outputs/apk/release/app-release.apk
